### PR TITLE
Make the contorls DSL lazy

### PR DESCRIPTION
**Pull request by elia**
Avoid requiring the db if a control's value is fetched from it.

### CODE REVIEW

**Comment by jonspalmer** [comment]
Doing something that needs to be lazy in the controls strikes me as a code smell.
Could you provide a few more details on why this pattern is necessary. Please include details of before and after in terms of when the controls get evaluated and how it helps the pattern you are worried about. 

Also to accept any PR we will need specs around the behavior.

**Comment by elia** [comment]
> Also to accept any PR we will need specs around the behavior.

Yes, for sure! I left the PR in draft mode because I'm aware it requires more work and at the same time allow for early feedback 👍 

> Could you provide a few more details…

[This comment](https://github.com/jonspalmer/view_component_storybook/pull/39#issuecomment-864419123) has the whole backstory for the two contributions. In general I agree it's a smell but there are a good amount of cases in which it's legit, for example if you have configuration data and similar things.

We're also striving for creating functional components that only accept primitive values, but any ruby object that's not a json serializable hash will potentially require similar features.

What are your thoughts?

**Comment by jonspalmer** [comment]
@elia Still getting used to the "Draft mode" - sorry I missed this. This is certainly a feature set that it would be nice to explore - I'd like to think a little bit about various ways to implement it.

Can you layout the difference in execution when controls are lazy in the PR vs before? I haven't gone through and understood the call tree to know what this is saving. I'm sure you have. Can you share?

**Comment by jonspalmer** [comment]
> We're also striving for creating functional components that only accept primitive values, but any ruby object that's not a json serializable hash will potentially require similar features.

I'd agree that its admirable to create functional components with primitive values but its often very impractical and brittle. In general my rule has been that we don't really want View Components to be doing DB operations and other reads - like an API. View Components are View layer concerns and, in general, their data should be prepared for them. ie pass in a `User` object vs a `user_id` for which the VC does `User.find(user_id)` which is just asking for N+1 kinds of problems. It's also much harder to test a VC if it has read logic.

> for example if you have configuration data and similar things

Could you share a few more of these examples. They're not obvious to me and it would help to understand them.

**Comment by jonspalmer** [comment]
Can we also talk about what `lazy` behavior is giving us. There are two main possibilities a) avoiding making the call until its really needed b) deferring the call to a later time. What's the balance in the use cases you are exploring. Making things lazy has little to no impact at time of writing the json stories because we have to iterate all stories and all controls. (In your example of pulling control values from an external CRM this has some very interesting consequences in terms of how stories stay in sync etc. plus external dependencies in your build pipeline). 

Is the main advantage of being 'lazy' that your web app servers only need to resolve the controls if they're called on to server the story html and we're calling `values_from_params` for a specific story?

**Comment by elia** [comment]
The original issue we had was that it was executing everything during initialization, and that was failing both our CI and deploys when the environment wasn't able to access external resources, like at build time during deploys etc.

**Comment by jonspalmer** [comment]
I wonder if we can aim for a more targeted fix. Rather than making the entire controls block lazy, which I worry might have other consequences, can we instead offer support for making various attributes of the control take a block. I'm not sure the example in #39 actually demonstrates the problem you explain during initialization. Perhaps we can agree a more accurate example of the problem and explore options?

**Comment by elia** [comment]
Sure, we're in the process of mirroring a number of components from the design system in Figma to storybook. So I think we'll be able to battle test any solution we want to try. 

The last two components I added to storybook had to take in a very complex active record object and after initially trying to pass a block to controls I eventually ended up customizing values_from_params and manipulated the whole hash. 

Eventually I expect to need to customize the component's initialization and expose in storybook some simple knobs and a sort of preset control (eg using the string "last" as a proxy for fetching the last record). 

(Hope this makes sense, I'm writing from mobile, I'll add some examples when I get back to a keyboard)

**Comment by elia** [comment]
@jonspalmer here's an example of overriding values_from_params:

```rb
  story(:default) do
    controls do
      text(:order, "latest")
    end

    def story_config.values_from_params(params)
      params = super

      params[:order] =
        case params[:order]
        when 'latest' then Spree::Order.last
        when /^R\d+/ then Spree::Order.find_by(number: params[:order])
        when /^\d+/ then Spree::Order.find_by(id: params[:order])
        else raise "unsupported format"
        end

      params
    end
  end
```

This is still work in progress and will probably be extracted in some way, but I posted it anyway to add some context.

**Comment by jonspalmer** [comment]
@elia these are helpful. However, overriding `values_from_params` isn't a need for making the DSL lazy right? `values_from_params` is a pure run time concern.

**Comment by jonspalmer** [comment]
The controls DSL that this PR references is now deprecated. In its place we now have custom controls which I believe could  be enough to satisfy the "lazy" need. It would be great to have some stronger use cases described to test that theory against. Please open an issue or another PR if there are additional things we can add to support the use cases

**Pull request closed without merging**
