### PR TITLE
Add an example on how to add custom controls

### PR DESCRIPTION
**Pull request by elia**
This was adapted from a real world case.

cc @nerfologist

### CODE REVIEW

**Comment by jonspalmer** [comment]
Documentation of adding custom controls is great. This strikes me as a fine example of transforming a string parameter into a more complicated object via a custom control. 

However, two comments on the specific example:
1. I would probably expect three stories, one for each role, vs a story with a role chooser control. IMO this more strongly documents the expected states of the component.
2. Loading data from the DB like this in a story is something of a smell. I think of stories a bit like tests. You want the data they rely on to be repeatable and fixture like. Having your Stories behave differently for different developers environments or differently in your prod environment would be very strange. You risk Exposing sensitive User data in your production environment etc. The story might raise exceptions if there are no matching Users in the DB. Instead I would expect to construct a User by hand in the story vs loading from the DB.

**Comment by elia** [comment]
Yeah, thanks for the feedback, that's awesome!

It is indeed coming from the need to map query parameters to mode complicated object that can be then passed to the component.

I'm sorry about the misleading example, it's admittedly contrived and I made up the roles thing to map other stuff that was too specific to the app domain, we can surely do better 👍 😅 

Specifically the original example was loading stuff from a headless CMS instead of the DB and the list of items is dynamic and defined there, so it's not suitable for different stories but we still need to inspect the result of every entry.

---

I'm open to suggestions of any kind, my only aim is to save some effort for the next user that needs to customize a control. 😊

**Comment by jonspalmer** [comment]
How about an example like converting a string param to a Class via `constantize` or the like?

**Comment by jonspalmer** [comment]
With the new features in main we can now support this 'out of the box':

```ruby
    ROLES = {
      admin: "Admin user"
      guest: "Guest user"
      default: "Default user"
    }

  story(:default) do
    constructor(
      user: custom(select(ROLES, 'admin') do |role|
         User.with_role(role).first!
      end
    end
  end
  ```
  
  which I hope you'll agree is pretty slick.
  
  We need docs on all this stuff. Would appreciate contributions to #54

**Comment by jonspalmer** [comment]
Closing this as we now have support for custom controls built in.

**Comment by elia** [comment]
Thanks for fixing this! 🙏

**Pull request closed without merging**
